# Exploratory Data Analysis and Data Cleaning, Python 3

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
# import data
tap = pd.read_csv("TAP_data.csv")
print(tap.shape)

(190964, 17)

From the above

,Academic Year,Level,TAP Level of Study,Sector Type,TAP Sector Group,Recipient Age Group,TAP Financial Status,TAP Award Schedule,TAP Degree or NonDegree,TAP Schedule Letter,"Income by $1,000 Range","Income by $5,000 Range","Income by $10,000 Range",TAP Recipient Headcount,TAP Recipient FTEs,TAP Recipient Dollars,Award per FTE
0,2015,U,4 yr Undergrad,PRIVATE,6-BUS. DEGREE,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,E,"$ 1,001 to $ 2,000","$ 1 to $ 5,000","$ 0 to $10,000",23,18.92,"$96,170.20","$5,082.99"
1,2015,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,age 26 - 35,Financial_Independent,Independent_Schedule,Degree,M,"$ 6,001 to $ 7,000","$ 5,001 to $10,000","$ 0 to $10,000",10,6.20,"$11,802.47","$1,903.62"
2,2015,U,4 yr Undergrad,PRIVATE,6-BUS. DEGREE,age 26 - 35,Financial_Dependent,Dependent_Schedule,Degree,E,"$ 2,001 to $ 3,000","$ 1 to $ 5,000","$ 0 to $10,000",1,0.17,$847.96,"$4,988.00"
3,2015,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$12,001 to $13,000","$10,001 to $15,000","$10,001 to $20,000",12,10.30,"$48,704.45","$4,728.59"
4,2015,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,age 26 - 35,Financial_Independent,Dependent_Schedule,Degree,E,"$25,001 to $26,000","$25,001 to $30,000","$20,001 to $30,000",2,1.51,"$4,951.94","$3,279.43"
5,2015,U,4 yr Undergrad,PUBLIC,3-SUNY SO,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$23,001 to $24,000","$20,001 to $25,000","$20,001 to $30,000",58,48.06,"$167,056.86","$3,476.01"
6,2015,U,2 yr Undergrad,PRIVATE,8-OTHER,age 26 - 35,Financial_Independent,Independent_Schedule,Degree,M,"$ 1 to $ 1,000","$ 1 to $ 5,000","$ 0 to $10,000",1,0.50,"$1,462.50","$2,925.00"
7,2015,U,4 yr Undergrad,PRIVATE,6-BUS. DEGREE,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,E,"$ 5,001 to $ 6,000","$ 5,001 to $10,000","$ 0 to $10,000",26,23.35,"$118,749.79","$5,085.64"
8,2015,U,4 yr Undergrad,PUBLIC,3-SUNY SO,age 36 - 50,Financial_Independent,Dependent_Schedule,Degree,E,"$ 2,001 to $ 3,000","$ 1 to $ 5,000","$ 0 to $10,000",14,11.01,"$56,055.55","$5,091.33"
9,2015,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,over age 50,Financial_Independent,Dependent_Schedule,Degree,E,"$65,001 to $66,000","$65,001 to $70,000","$60,001 to $70,000",1,1.01,$502.58,$497.60
10,2015,U,2 yr Undergrad,PRIVATE,7-BUS. NON-DEG,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,E,"$ 3,001 to $ 4,000","$ 1 to $ 5,000","$ 0 to $10,000",6,6.07,"$24,045.84","$3,961.42"
11,2015,U,2 yr Undergrad,PUBLIC,4-SUNY CC,age 36 - 50,Financial_Independent,Dependent_Schedule,Degree,E,"$13,001 to $14,000","$10,001 to $15,000","$10,001 to $20,000",28,20.28,"$74,048.60","$3,651.31"
12,2015,U,4 yr Undergrad,PRIVATE,6-BUS. DEGREE,age 26 - 35,Financial_Dependent,Dependent_Schedule,Degree,E,"$45,001 to $46,000","$45,001 to $50,000","$40,001 to $50,000",1,0.50,$384.22,$768.44
13,2015,U,2 yr Undergrad,PRIVATE,6-BUS. DEGREE,age 36 - 50,Financial_Independent,Dependent_Schedule,Degree,E,"$54,001 to $55,000","$50,001 to $55,000","$50,001 to $60,000",2,1.00,$502.24,$502.24
14,2015,U,4 yr Undergrad,PUBLIC,3-SUNY SO,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$23,001 to $24,000","$20,001 to $25,000","$20,001 to $30,000",600,545.68,"$1,897,822.12","$3,477.90"
15,2015,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,age 22 - 25,Financial_Independent,Married_No_Dependents,Degree,C,$0,$0,"$ 0 to $10,000",8,4.69,"$14,139.30","$3,014.78"
16,2015,U,2 yr Undergrad,PRIVATE,8-OTHER,age 36 - 50,Financial_Independent,Independent_Schedule,Degree,M,$0,$0,"$ 0 to $10,000",2,1.50,"$4,537.50","$3,025.00"
17,2015,U,4 yr Undergrad,PUBLIC,4-SUNY CC,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$ 1 to $ 1,000","$ 1 to $ 5,000","$ 0 to $10,000",14,12.27,"$62,133.81","$5,063.88"
18,2015,U,4 yr Undergrad,PRIVATE,6-BUS. DEGREE,age 26 - 35,Financial_Dependent,Dependent_Schedule,Degree,E,"$ 7,001 to $ 8,000","$ 5,001 to $10,000","$ 0 to $10,000",2,2.01,"$10,109.64","$5,029.67"
19,2015,U,4 yr Undergrad,PUBLIC,1-CUNY SR,age 36 - 50,Financial_Independent,Dependent_Schedule,Degree,E,"$ 2,001 to $ 3,000","$ 1 to $ 5,000","$ 0 to $10,000",12,8.30,"$42,353.72","$5,102.86"
20,2015,U,4 yr Undergrad,PRIVATE,6-BUS. DEGREE,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,E,"$46,001 to $47,000","$45,001 to $50,000","$40,001 to $50,000",5,5.86,"$4,164.77",$710.71
21,2015,U,2 yr Undergrad,PUBLIC,4-SUNY CC,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$17,001 to $18,000","$15,001 to $20,000","$10,001 to $20,000",652,511.55,"$1,691,148.04","$3,305.93"
22,2015,U,2 yr Undergrad,PUBLIC,2-CUNY CC,age 26 - 35,Financial_Independent,Dependent_Schedule,Degree,E,"$29,001 to $30,000","$25,001 to $30,000","$20,001 to $30,000",18,11.52,"$27,586.26","$2,394.64"
23,2015,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,E,"$76,001 to $77,000","$75,001 to $80,000","$70,001 to $80,000",1,1.01,$502.58,$497.60
24,2015,U,2 yr Undergrad,PRIVATE,7-BUS. NON-DEG,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$ 2,001 to $ 3,000","$ 1 to $ 5,000","$ 0 to $10,000",6,6.58,"$26,121.37","$3,969.81"
25,2015,U,2 yr Undergrad,PUBLIC,1-CUNY SR,age 26 - 35,Financial_Independent,Dependent_Schedule,Degree,E,"$40,001 to $41,000","$40,001 to $45,000","$40,001 to $50,000",1,0.50,$723.57,"$1,447.14"
26,2015,U,2 yr Undergrad,PUBLIC,4-SUNY CC,over age 50,Financial_Independent,Dependent_Schedule,Degree,A,"$ 3,001 to $ 4,000","$ 1 to $ 5,000","$ 0 to $10,000",2,1.00,"$3,695.21","$3,695.21"
27,2015,U,2 yr Undergrad,PUBLIC,2-CUNY CC,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$ 5,001 to $ 6,000","$ 5,001 to $10,000","$ 0 to $10,000",707,509.83,"$2,439,922.65","$4,785.76"
28,2015,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,over age 50,Financial_Independent,Dependent_Schedule,Degree,A,"$17,001 to $18,000","$15,001 to $20,000","$10,001 to $20,000",1,0.50,"$1,369.54","$2,739.08"
29,2015,U,4 yr Undergrad,PRIVATE,6-BUS. DEGREE,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$44,001 to $45,000","$40,001 to $45,000","$40,001 to $50,000",13,13.73,"$13,384.91",$974.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190934,2000,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,E,"$21,001 to $22,000","$20,001 to $25,000","$20,001 to $30,000",4,4.00,"$14,313.00","$3,578.25"
190935,2000,U,5 yr Undergrad,PUBLIC,1-CUNY SR,age 26 - 35,Financial_Independent,Dependent_Schedule,Degree,D,"$ 1 to $ 1,000","$ 1 to $ 5,000","$ 0 to $10,000",2,1.00,"$2,890.00","$2,890.00"
190936,2000,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,E,"$66,001 to $67,000","$65,001 to $70,000","$60,001 to $70,000",1,1.00,$325.00,$325.00
190937,2000,U,5 yr Undergrad,PUBLIC,1-CUNY SR,under age 22,Financial_Independent,Dependent_Schedule,Degree,D,"$ 1 to $ 1,000","$ 1 to $ 5,000","$ 0 to $10,000",1,0.75,"$2,438.75","$3,251.67"
190938,2000,U,2 yr Undergrad,PUBLIC,3-SUNY SO,under age 22,Financial_Dependent,Dependent_Schedule,Degree,D,"$17,001 to $18,000","$15,001 to $20,000","$10,001 to $20,000",1,0.50,"$1,088.00","$2,176.00"
190939,2000,U,5 yr Undergrad,PUBLIC,1-CUNY SR,age 22 - 25,Financial_Independent,Dependent_Schedule,Degree,D,"$ 2,001 to $ 3,000","$ 1 to $ 5,000","$ 0 to $10,000",2,1.50,"$3,590.00","$2,393.33"
190940,2000,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$67,001 to $68,000","$65,001 to $70,000","$60,001 to $70,000",8,7.50,"$2,437.50",$325.00
190941,2000,U,5 yr Undergrad,PUBLIC,1-CUNY SR,age 22 - 25,Financial_Independent,Dependent_Schedule,Degree,D,"$ 3,001 to $ 4,000","$ 1 to $ 5,000","$ 0 to $10,000",7,5.75,"$16,627.00","$2,891.65"
190942,2000,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$22,001 to $23,000","$20,001 to $25,000","$20,001 to $30,000",6,5.50,"$19,187.50","$3,488.64"
190943,2000,U,5 yr Undergrad,PUBLIC,1-CUNY SR,under age 22,Financial_Independent,Dependent_Schedule,Degree,D,"$ 3,001 to $ 4,000","$ 1 to $ 5,000","$ 0 to $10,000",1,0.50,"$1,445.00","$2,890.00"
190944,2000,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$68,001 to $69,000","$65,001 to $70,000","$60,001 to $70,000",1,0.50,$162.50,$325.00
190945,2000,U,5 yr Undergrad,PUBLIC,1-CUNY SR,age 26 - 35,Financial_Independent,Dependent_Schedule,Degree,D,"$ 4,001 to $ 5,000","$ 1 to $ 5,000","$ 0 to $10,000",2,1.00,"$2,890.00","$2,890.00"
190946,2000,U,2 yr Undergrad,PUBLIC,1-CUNY SR,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,D,"$35,001 to $36,000","$35,001 to $40,000","$30,001 to $40,000",6,4.33,"$1,841.67",$425.33
190947,2000,U,5 yr Undergrad,PUBLIC,1-CUNY SR,age 36 - 50,Financial_Independent,Dependent_Schedule,Degree,D,"$ 5,001 to $ 6,000","$ 5,001 to $10,000","$ 0 to $10,000",2,1.00,"$2,890.00","$2,890.00"
190948,2000,U,2 yr Undergrad,PRIVATE,5-INDEPENDENT,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$69,001 to $70,000","$65,001 to $70,000","$60,001 to $70,000",6,6.00,"$1,950.00",$325.00
190949,2000,U,5 yr Undergrad,PUBLIC,1-CUNY SR,age 22 - 25,Financial_Independent,Dependent_Schedule,Degree,D,"$ 6,001 to $ 7,000","$ 5,001 to $10,000","$ 0 to $10,000",2,1.00,"$2,890.00","$2,890.00"
190950,2000,G,2 yr Undergrad,PRIVATE,6-BUS. DEGREE,age 36 - 50,Financial_Independent,Independent_Schedule,Degree,V,$0,$0,"$ 0 to $10,000",1,1.00,$550.00,$550.00
190951,2000,G,2 yr Undergrad,PUBLIC,3-SUNY SO,age 36 - 50,Financial_Independent,Dependent_Schedule,Degree,U,"$ 4,001 to $ 5,000","$ 1 to $ 5,000","$ 0 to $10,000",2,1.50,$518.50,$345.67
190952,2000,U,2 yr Undergrad,PUBLIC,1-CUNY SR,age 26 - 35,Financial_Dependent,Dependent_Schedule,Degree,A,"$ 1 to $ 1,000","$ 1 to $ 5,000","$ 0 to $10,000",2,1.00,"$3,040.00","$3,040.00"
190953,2000,U,2 yr Undergrad,PUBLIC,1-CUNY SR,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,A,"$13,001 to $14,000","$10,001 to $15,000","$10,001 to $20,000",1,0.50,"$1,189.00","$2,378.00"
190954,2000,U,2 yr Undergrad,PUBLIC,1-CUNY SR,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,D,$0,$0,"$ 0 to $10,000",172,115.29,"$341,936.87","$2,965.88"
190955,2000,U,2 yr Undergrad,PUBLIC,1-CUNY SR,age 22 - 25,Financial_Dependent,Dependent_Schedule,Degree,D,"$ 5,001 to $ 6,000","$ 5,001 to $10,000","$ 0 to $10,000",15,10.25,"$30,382.00","$2,964.10"
190956,2000,U,2 yr Undergrad,PUBLIC,1-CUNY SR,under age 22,Financial_Dependent,Dependent_Schedule,Degree,D,"$16,001 to $17,000","$15,001 to $20,000","$10,001 to $20,000",42,31.04,"$67,697.74","$2,180.98"
190957,2000,U,2 yr Undergrad,PUBLIC,1-CUNY SR,under age 22,Financial_Dependent,Dependent_Schedule,Degree,D,"$49,001 to $50,000","$45,001 to $50,000","$40,001 to $50,000",2,1.00,$425.00,$425.00
190958,2000,U,2 yr Undergrad,PUBLIC,1-CUNY SR,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$50,001 to $51,000","$50,001 to $55,000","$50,001 to $60,000",17,12.50,"$5,312.50",$425.00
190959,2000,U,2 yr Undergrad,PUBLIC,1-CUNY SR,age 26 - 35,Financial_Independent,Dependent_Schedule,Degree,D,"$54,001 to $55,000","$50,001 to $55,000","$50,001 to $60,000",1,0.75,$318.75,$425.00
190960,2000,U,2 yr Undergrad,PUBLIC,2-CUNY CC,under age 22,Financial_Dependent,Dependent_Schedule,Degree,E,"$44,001 to $45,000","$40,001 to $45,000","$40,001 to $50,000",27,21.50,"$9,137.50",$425.00
190961,2000,U,2 yr Undergrad,PUBLIC,4-SUNY CC,age 26 - 35,Financial_Dependent,Dependent_Schedule,Degree,D,"$33,001 to $34,000","$30,001 to $35,000","$30,001 to $40,000",2,1.00,$425.00,$425.00
190962,2000,U,2 yr Undergrad,PRIVATE,8-OTHER,age 26 - 35,Financial_Independent,Dependent_Schedule,Degree,E,"$24,001 to $25,000","$20,001 to $25,000","$20,001 to $30,000",1,0.33,"$1,067.33","$3,234.33"
190963,2000,U,4 yr Undergrad,PUBLIC,1-CUNY SR,age 36 - 50,Financial_Independent,Dependent_Schedule,Degree,A,"$ 5,001 to $ 6,000","$ 5,001 to $10,000","$ 0 to $10,000",13,7.67,"$22,170.60","$2,890.56"